application: wunderlust-c7579
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries: 
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: matplotlib
  version: latest
- name: pycrypto
  version: latest
- name: lxml
  version: latest

handlers:
- url: /js/
  static_dir: js/
- url: /css/
  static_dir: css/
- url: /img/
  static_dir: img/
- url: /content/img
  static_dir: content/img
- url: /.*
  script: main.app

